name: Always Fail

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Hello World
        run: echo "Hello, World!"
        
      - name: Validate pull request, always fail
        run: exit 1
